import type { Position } from '@/types/player'

export const ADJACENT_POSITIONS: Partial<Record<Position, Position[]>> = {
  CENTER_BACK:                  ['LEFT_FULL_BACK', 'RIGHT_FULL_BACK'],
  LEFT_FULL_BACK:               ['LEFT_WING_BACK', 'CENTER_BACK'],
  RIGHT_FULL_BACK:              ['RIGHT_WING_BACK', 'CENTER_BACK'],
  LEFT_WING_BACK:               ['LEFT_FULL_BACK', 'WINGER'],
  RIGHT_WING_BACK:              ['RIGHT_FULL_BACK', 'WINGER'],
  CENTRAL_DEFENSIVE_MIDFIELDER: ['LEFT_DEFENSIVE_MIDFIELDER', 'RIGHT_DEFENSIVE_MIDFIELDER', 'CENTRAL_ATTACK_MIDFIELDER'],
  LEFT_DEFENSIVE_MIDFIELDER:    ['CENTRAL_DEFENSIVE_MIDFIELDER'],
  RIGHT_DEFENSIVE_MIDFIELDER:   ['CENTRAL_DEFENSIVE_MIDFIELDER'],
  CENTRAL_ATTACK_MIDFIELDER:    ['LEFT_ATTACK_MIDFIELDER', 'RIGHT_ATTACK_MIDFIELDER', 'CENTRAL_DEFENSIVE_MIDFIELDER'],
  LEFT_ATTACK_MIDFIELDER:       ['CENTRAL_ATTACK_MIDFIELDER', 'WINGER'],
  RIGHT_ATTACK_MIDFIELDER:      ['CENTRAL_ATTACK_MIDFIELDER', 'WINGER'],
  WINGER:                       ['LEFT_ATTACK_MIDFIELDER', 'RIGHT_ATTACK_MIDFIELDER'],
  STRIKER:                      ['SHADOW_STRIKER'],
  SHADOW_STRIKER:               ['STRIKER', 'CENTRAL_ATTACK_MIDFIELDER'],
}
