ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INJURY_REHABILITATING_STARTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INJURY_REPORT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TRAINING_HIGH_PERFORMANCE_PLAYER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TRAINING_HIGH_PERFORMANCE_SELF';
