import { useState } from 'react'
import { toast } from 'sonner'
import { useTranslation } from 'react-i18next'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { budgetPlanApi } from '@/services/financial-report.service'
import type { BudgetPlan } from '@/types/budget'
import type { ExpenseCategory } from '@/types/expense-category'

function fmt(n: number) {
  return n.toLocaleString('ko-KR') + '원'
}

interface Props {
  seasonId: number
  plan: BudgetPlan | null
  categories: ExpenseCategory[]
  labelOf: (code: string) => string
  /** Called after any advanced action mutates server state so the parent can reload. */
  onServerMutated: () => Promise<void>
}

/**
 * Advanced actions that don't fit the linear wizard: Knapsack optimize,
 * auto-generate from prior season revenue growth, and emergency override
 * logging. Rendered on the wizard's final page below the category editors.
 */
export function BudgetAdvancedPanel({
  seasonId,
  plan,
  categories,
  labelOf,
  onServerMutated,
}: Props) {
  const { t } = useTranslation('admin')

  const [optimizing, setOptimizing] = useState(false)

  // Auto-generate flow (confirm → form → submit)
  const [autoGenDialog, setAutoGenDialog] = useState<'closed' | 'confirm' | 'form'>('closed')
  const [autoGenRate, setAutoGenRate] = useState('10')
  const [autoGenContingency, setAutoGenContingency] = useState('0')
  const [autoGenerating, setAutoGenerating] = useState(false)
  const [zeroWarnings, setZeroWarnings] = useState<string[]>([])

  // Override form
  const defaultOverrideCategory = categories[0]?.code ?? ''
  const [overrideCategory, setOverrideCategory] = useState<string>(defaultOverrideCategory)
  const [overrideAmount, setOverrideAmount] = useState('')
  const [overrideReason, setOverrideReason] = useState('')

  const handleOptimize = async () => {
    setOptimizing(true)
    try {
      await budgetPlanApi.optimize(seasonId)
      await onServerMutated()
      toast.success(t('budget.optimized'))
    } catch (err) {
      toast.error(err instanceof Error ? err.message : t('budget.optimizeFailed'))
    } finally {
      setOptimizing(false)
    }
  }

  const handleAutoGenerate = async () => {
    setAutoGenerating(true)
    try {
      const result = await budgetPlanApi.autoGenerate(seasonId, {
        growthRate: parseFloat(autoGenRate) / 100,
        contingencyRate: parseFloat(autoGenContingency) / 100 || undefined,
      })
      setZeroWarnings(result.zeroCategories)
      await onServerMutated()
      setAutoGenDialog('closed')
      toast.success(t('budget.autoGenerated'))
    } catch (err) {
      toast.error(err instanceof Error ? err.message : t('budget.autoGenerateFailed'))
    } finally {
      setAutoGenerating(false)
    }
  }

  const handleOverride = async () => {
    try {
      await budgetPlanApi.addOverride(seasonId, {
        category: overrideCategory,
        amount: parseInt(overrideAmount, 10),
        reason: overrideReason,
      })
      await onServerMutated()
      setOverrideAmount('')
      setOverrideReason('')
      toast.success(t('budget.overrideLogged'))
    } catch (err) {
      toast.error(err instanceof Error ? err.message : t('budget.overrideFailed'))
    }
  }

  return (
    <Card className="border-dashed">
      <CardHeader>
        <CardTitle className="text-base">고급 기능</CardTitle>
        <p className="text-xs text-muted-foreground">
          Knapsack 자동 배분, 이전 시즌 기반 자동 생성, 긴급지출 override 기록
        </p>
      </CardHeader>
      <CardContent className="space-y-6">
        {zeroWarnings.length > 0 && (
          <div className="rounded-md bg-yellow-50 border border-yellow-200 px-3 py-2 text-sm text-yellow-800">
            {t('budget.zeroCategoriesWarning')}{' '}
            {zeroWarnings.map((c) => labelOf(c)).join(', ')}
          </div>
        )}

        {/* Knapsack + Auto-generate action row */}
        <div className="flex flex-wrap gap-2">
          <Button variant="outline" onClick={handleOptimize} disabled={optimizing}>
            {optimizing ? t('budget.optimizing') : t('budget.optimize')}
          </Button>
          <Button
            variant="outline"
            onClick={() => setAutoGenDialog(plan ? 'confirm' : 'form')}
          >
            {t('budget.autoGenerate')}
          </Button>
        </div>

        {/* Knapsack allocation summary — only shown once optimize has run */}
        {plan?.budgetCategoryPlans.some((cp) => cp.knapsackAllocated != null) && (
          <div className="space-y-1">
            <Label className="text-xs">Knapsack 배분 결과</Label>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-1 text-xs">
              {plan.budgetCategoryPlans
                .filter((cp) => cp.knapsackAllocated != null)
                .map((cp) => {
                  const actual = plan.actuals?.[cp.category] ?? 0
                  return (
                    <div
                      key={cp.id}
                      className="flex items-center justify-between border rounded px-2 py-1"
                    >
                      <span className="truncate">{labelOf(cp.category)}</span>
                      <Badge variant="outline" className="text-[10px] whitespace-nowrap">
                        {fmt(cp.knapsackAllocated ?? 0)} / {fmt(actual)}
                      </Badge>
                    </div>
                  )
                })}
            </div>
          </div>
        )}

        {/* Override log */}
        <div className="space-y-3 border-t pt-4">
          <div>
            <Label className="text-sm font-semibold">{t('budget.overrideSection')}</Label>
          </div>
          <div className="grid grid-cols-3 gap-2">
            <select
              className="border rounded px-2 py-1 text-sm bg-background"
              value={overrideCategory}
              onChange={(e) => setOverrideCategory(e.target.value)}
            >
              {categories.map((c) => (
                <option key={c.code} value={c.code}>
                  {c.label}
                </option>
              ))}
            </select>
            <Input
              placeholder={t('budget.overrideAmount')}
              type="number"
              value={overrideAmount}
              onChange={(e) => setOverrideAmount(e.target.value)}
            />
            <Input
              placeholder={t('budget.overrideReason')}
              value={overrideReason}
              onChange={(e) => setOverrideReason(e.target.value)}
            />
          </div>
          <Button
            size="sm"
            variant="outline"
            onClick={handleOverride}
            disabled={!overrideCategory || !overrideAmount}
          >
            {t('budget.logOverride')}
          </Button>

          {(plan?.overrideLogs ?? []).length > 0 && (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="text-xs">{t('budget.col.category')}</TableHead>
                  <TableHead className="text-xs">{t('budget.col.amount')}</TableHead>
                  <TableHead className="text-xs">{t('budget.col.reason')}</TableHead>
                  <TableHead className="text-xs">{t('budget.col.date')}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {plan!.overrideLogs.map((log) => (
                  <TableRow key={log.id}>
                    <TableCell className="text-xs">{labelOf(log.category)}</TableCell>
                    <TableCell className="text-xs tabular-nums">{fmt(log.amount)}</TableCell>
                    <TableCell className="text-xs">{log.reason}</TableCell>
                    <TableCell className="text-xs tabular-nums">
                      {new Date(log.createdAt).toLocaleDateString('ko-KR')}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </div>
      </CardContent>

      {/* Auto-generate: overwrite confirm dialog */}
      <Dialog
        open={autoGenDialog === 'confirm'}
        onOpenChange={(o) => !o && setAutoGenDialog('closed')}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('budget.autoGenerateConfirmTitle')}</DialogTitle>
          </DialogHeader>
          <p className="text-sm text-muted-foreground">
            {t('budget.autoGenerateConfirmDesc')}
          </p>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAutoGenDialog('closed')}>
              {t('budget.autoGenerateCancel')}
            </Button>
            <Button onClick={() => setAutoGenDialog('form')}>
              {t('budget.autoGenerateConfirm')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto-generate: parameter form dialog */}
      <Dialog
        open={autoGenDialog === 'form'}
        onOpenChange={(o) => !o && setAutoGenDialog('closed')}
      >
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{t('budget.autoGenerate')}</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-1.5">
              <Label>{t('budget.growthRate')}</Label>
              <Input
                type="number"
                value={autoGenRate}
                onChange={(e) => setAutoGenRate(e.target.value)}
                placeholder="10"
              />
            </div>
            <div className="space-y-1.5">
              <Label>{t('budget.contingencyRateLabel')}</Label>
              <Input
                type="number"
                value={autoGenContingency}
                onChange={(e) => setAutoGenContingency(e.target.value)}
                placeholder="0"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setAutoGenDialog('closed')}>
              {t('budget.autoGenerateCancel')}
            </Button>
            <Button onClick={handleAutoGenerate} disabled={autoGenerating}>
              {autoGenerating ? t('budget.autoGenerating') : t('budget.autoGenerate')}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </Card>
  )
}
