-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPONSORSHIP_EXPIRY_90D';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPONSORSHIP_EXPIRY_60D';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'SPONSORSHIP_EXPIRY_30D';
