-- Fix missing FrontOfficeRole enum values caused by skipped migration 20260804000000
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'FINANCE_MANAGER';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'ASSET_MANAGER';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'HR_MANAGER';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'FACILITY_MANAGER';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'HR_STAFF';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'ASSET_STAFF';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'FINANCE_STAFF';
ALTER TYPE "FrontOfficeRole" ADD VALUE IF NOT EXISTS 'FACILITY_STAFF';
