-- prisma-migrate-no-transaction

ALTER TYPE "CoachingRole" ADD VALUE IF NOT EXISTS 'MEDICAL_DIRECTOR';
ALTER TYPE "SessionType" ADD VALUE IF NOT EXISTS 'GOALKEEPER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EQUIPMENT_LOW_STOCK';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXTENSION_OPTION_AVAILABLE';

CREATE TYPE "FrontOfficeRole" AS ENUM ('GM', 'TD', 'CONTRACT_MANAGER', 'SCOUT', 'EQUIPMENT_MANAGER', 'TACTICAL_ANALYST');
CREATE TYPE "TacticalStatus" AS ENUM ('DRAFT', 'CONFIRMED');

ALTER TABLE "User" ADD COLUMN "frontOfficeRole" "FrontOfficeRole";

ALTER TABLE "TacticalAnalysis" ADD COLUMN "status" "TacticalStatus" NOT NULL DEFAULT 'DRAFT';

ALTER TABLE "Notification" ADD COLUMN "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Notification" ADD COLUMN "body" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Notification" ADD COLUMN "readAt" TIMESTAMP(3);
ALTER TABLE "Notification" DROP COLUMN IF EXISTS "message";
ALTER TABLE "Notification" DROP COLUMN IF EXISTS "isRead";
