ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_BUDGET_REVERIFIED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_DISPATCH_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_DISPATCHED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'HIRING_DISPATCH_PERMISSION_REQUESTED';
