CREATE TYPE "PlayStyle" AS ENUM (
  'SWEEPER_KEEPER', 'TRADITIONAL_GK',
  'BALL_PLAYING_CB', 'STOPPER', 'LIBERO',
  'INVERTED_FULLBACK', 'OVERLAPPING_WINGBACK', 'DEFENSIVE_WINGBACK',
  'REGISTA', 'HALF_BACK', 'DEFENSIVE_MIDFIELDER',
  'BOX_TO_BOX', 'MEZZALA', 'CARRILERO', 'DEEP_LYING_PLAYMAKER',
  'TREQUARTISTA', 'ADVANCED_PLAYMAKER',
  'INVERTED_WINGER', 'INSIDE_FORWARD', 'WIDE_MIDFIELDER',
  'FALSE_9', 'TARGET_MAN', 'POACHER', 'COMPLETE_FORWARD', 'PRESSING_FORWARD'
);

ALTER TABLE "Player" ALTER COLUMN "playStyle" TYPE "PlayStyle" USING "playStyle"::"PlayStyle";
ALTER TABLE "Prospect" ADD COLUMN "playStyle" "PlayStyle";
