import { Router } from "express";
import adminRouter from "./admin/admin.routes";
import reportRouter from "./report/report.routes";
import analysisRouter from "./analysis/analysis.routes";
import authRouter from "./auth/auth.routes";
import dashboardRouter from "./dashboard/dashboard.routes";
import contractRouter from "./contract/contract.routes";
import countryRouter from "./country/country.routes";
import equipmentRouter from "./equipment/equipment.routes";
import partnerRouter from "./partner/partner.routes";
import injuryRouter from "./injury/injury.routes";
import matchRouter from "./match/match.routes";
import notificationRouter from "./notification/notification.routes";
import playerRouter from "./player/player.routes";
import prospectRouter from "./prospect/prospect.routes";
import seasonRouter from "./season/season.routes";
import tacticalRouter from "./tactical/tactical.routes";
import trainingRouter from "./training/training.routes";
import transferRouter from "./transfer/transfer.routes";
import medicalExpenseRouter from "./medical-expense/medical-expense.routes";
import coachRouter from "./coach/coach.routes";
import videoRouter from "./video/video.routes";
import trainingReferenceRouter from "./training-reference/training-reference.routes";
import developmentPlanRouter from "./development-plan/development-plan.routes";
import coachAvailabilityRouter from "./coach-availability/coach-availability.routes";
import trainingLoadRouter from "./training-load/training-load.routes";
import teamRouter from "./team/team.routes";
import playerCallupRouter from "./player-callup/player-callup.routes";
import youthRegistrationRouter from "./youth-registration/youth-registration.routes";
import incidentReportRouter from "./incident-report/incident-report.routes";
import growthReportRouter from "./growth-report/growth-report.routes";
import safeguardRouter from "./safeguard/safeguard.routes";
import academyFeeRouter from "./academy-fee/academy-fee.routes";
import coachingStaffRouter from "./coaching-staff/coaching-staff.routes";
import clubSettingsRouter from "./club-settings/club-settings.routes";
import staffRecordRouter from "./staff-record/staff-record.routes";
import financialReportRouter from "./financial-report/financial-report.routes";
import departmentRouter from "./department/department.routes";
import operatingExpenseRouter from "./operating-expense/operating-expense.routes";
import hrReportRouter from "./hr-report/hr-report.routes";
import recruitmentRouter from "./recruitment/recruitment.routes";
import facilityRouter from "./facility/facility.routes";
import sponsorshipRouter from "./sponsorship/sponsorship.routes";
import payrollRouter from "./payroll/payroll.routes";
import hiringAutomationRouter from "./hiring-automation/hiring-automation.routes";
import clubRouter from "./club/club.routes";
import leagueRouter from "./league/league.routes";
import guardianRouter from "./guardian/guardian.routes";
import hrRouter from "./hr/hr.routes";
import softwareLicenseRouter from "./software-license/software-license.routes";
import ledgerRouter from "./ledger/ledger.routes";
import salesRouter from "./sales/sales.routes";
import inventoryRouter from "./inventory/inventory.routes";
import agencyRouter from "./agency/agency.routes";
import transferRequestRouter from "./transfer-request/transfer-request.routes";
import opsReportRouter from "./ops-report/ops-report.routes";
import squadPlanRouter from "./squad-plan/squad-plan.routes";
import attendanceAppealRouter from "./attendance-appeal/attendance-appeal.routes";
import planReportRouter from "./plan-report/plan-report.routes";
import departmentReviewConfigRouter from "./department-review-config/department-review-config.routes";
import planReviewRouter from "./plan-review/plan-review.routes";
import hiringSurveyRouter from "./hiring-survey/hiring-survey.routes";
import formationSnapshotRouter from "./formation-snapshot/formation-snapshot.routes";
import certificationRouter from "./certification/certification.routes";
import budgetControlRouter from "./budget-control/budget-control.routes";
import budgetAutomationRouter from "./budget-automation/budget-automation.routes";
import expenseCategoryRouter from "./expense-category/expense-category.routes";
import assetRequestRouter from "./asset-request/asset-request.routes";
import hiringDispatchRouter from "./hiring-dispatch/hiring-dispatch.routes";
import hiringDocumentRouter from "./hiring-document/hiring-document.routes";
import medicalEquipmentLoanRouter from "./medical-equipment-loan/medical-equipment-loan.routes";
import { monthlySettlementRouter } from "./monthly-settlement/monthly-settlement.routes";
import { revenueAdjustmentRouter } from "./revenue-adjustment/revenue-adjustment.routes";
import { accountCodeRouter } from "./account-code/account-code.routes";
import { startCertStatusSyncJob } from "./jobs/certStatusSync";
import { startPreventiveScheduleGenJob } from "./jobs/preventiveScheduleGen";
import { startContactFollowUpNotifierJob } from "./jobs/contactFollowUpNotifier";

const apiRouter = Router();

apiRouter.get("/", (_req, res) => res.status(200).json({ status: "ok" }));

apiRouter.use("/admin", adminRouter);
apiRouter.use("/analysis", analysisRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/contracts", contractRouter);
apiRouter.use("/countries", countryRouter);
apiRouter.use("/equipment", equipmentRouter);
apiRouter.use("/partners", partnerRouter);
apiRouter.use("/injuries", injuryRouter);
apiRouter.use("/matches", matchRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/players", playerRouter);
apiRouter.use("/prospects", prospectRouter);
apiRouter.use("/seasons", seasonRouter);
apiRouter.use("/reports", reportRouter);
apiRouter.use("/medical-expenses", medicalExpenseRouter);
apiRouter.use("/coaches", coachRouter);
apiRouter.use("/tactical", tacticalRouter);
apiRouter.use("/training", trainingRouter);
apiRouter.use("/transfers", transferRouter);
apiRouter.use("/videos", videoRouter);
apiRouter.use("/training-references", trainingReferenceRouter);
apiRouter.use("/development-plans", developmentPlanRouter);
apiRouter.use("/coach-availabilities", coachAvailabilityRouter);
apiRouter.use("/training-loads", trainingLoadRouter);
apiRouter.use("/teams", teamRouter);
apiRouter.use("/clubs", clubRouter);
apiRouter.use("/player-callups", playerCallupRouter);
apiRouter.use("/youth-registrations", youthRegistrationRouter);
apiRouter.use("/incident-reports", incidentReportRouter);
apiRouter.use("/growth-reports", growthReportRouter);
apiRouter.use("/safeguard-reports", safeguardRouter);
apiRouter.use("/academy-fees", academyFeeRouter);
apiRouter.use("/coaching-staff", coachingStaffRouter);
apiRouter.use("/club-settings", clubSettingsRouter);
apiRouter.use("/departments", departmentRouter);
apiRouter.use("/staff-records", staffRecordRouter);
apiRouter.use("/financial-reports", financialReportRouter);
apiRouter.use("/operating-expenses", operatingExpenseRouter);
apiRouter.use("/hr-reports", hrReportRouter);
apiRouter.use("/recruitment", recruitmentRouter);
apiRouter.use("/sponsorships", sponsorshipRouter);
apiRouter.use("/facility", facilityRouter);
apiRouter.use("/payroll", payrollRouter);
apiRouter.use("/hiring-automation", hiringAutomationRouter);
apiRouter.use("/leagues", leagueRouter);
apiRouter.use("/guardians", guardianRouter);
apiRouter.use("/hr", hrRouter);
apiRouter.use("/software-licenses", softwareLicenseRouter);
apiRouter.use("/ledger", ledgerRouter);
apiRouter.use("/sales", salesRouter);
apiRouter.use("/inventory", inventoryRouter);
apiRouter.use("/agencies", agencyRouter);
apiRouter.use("/transfer-requests", transferRequestRouter);
apiRouter.use("/ops-reports", opsReportRouter);
apiRouter.use("/squad-plan", squadPlanRouter);
apiRouter.use("/attendance-appeals", attendanceAppealRouter);
apiRouter.use("/plan-reports", planReportRouter);
apiRouter.use("/department-review-configs", departmentReviewConfigRouter);
apiRouter.use("/plan-reviews", planReviewRouter);
apiRouter.use("/hiring-surveys", hiringSurveyRouter);
apiRouter.use("/formation-snapshots", formationSnapshotRouter);
apiRouter.use("/certification", certificationRouter);
apiRouter.use("/budget-control", budgetControlRouter);
apiRouter.use("/budget-automation", budgetAutomationRouter);
apiRouter.use("/expense-categories", expenseCategoryRouter);
apiRouter.use("/asset-requests", assetRequestRouter);
apiRouter.use("/hiring-dispatches", hiringDispatchRouter);
apiRouter.use("/hiring-documents", hiringDocumentRouter);
apiRouter.use("/medical-equipment-loan", medicalEquipmentLoanRouter);
apiRouter.use("/monthly-settlement", monthlySettlementRouter);
apiRouter.use("/revenue-adjustment", revenueAdjustmentRouter);
apiRouter.use("/account-codes", accountCodeRouter);

startCertStatusSyncJob();
startPreventiveScheduleGenJob();
startContactFollowUpNotifierJob();

export default apiRouter;
