ALTER TABLE "FinancialReport"
  ALTER COLUMN "totalRevenue" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueTicket" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueSponsorship" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueBroadcast" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueMerchandise" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueSubsidy" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueParentCompany" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueAcademyFee" TYPE DOUBLE PRECISION,
  ALTER COLUMN "revenueOther" TYPE DOUBLE PRECISION;
