-- Add new NotificationType enum values
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXTERNAL_REPORT_CREATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXTERNAL_REPORT_DUE_SOON';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EXTERNAL_REPORT_OVERDUE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEDICAL_EXPENSE_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEDICAL_EXPENSE_LEADER_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEDICAL_EXPENSE_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'MEDICAL_EXPENSE_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REPORT_SUBMITTED';

-- Add entityId column to Notification
ALTER TABLE "Notification" ADD COLUMN IF NOT EXISTS "entityId" INTEGER;
