ALTER TYPE "DeptRole" ADD VALUE IF NOT EXISTS 'LEADER';
ALTER TYPE "DeptRole" ADD VALUE IF NOT EXISTS 'DEPUTY';
ALTER TYPE "DeptRole" ADD VALUE IF NOT EXISTS 'SENIOR';
ALTER TYPE "DeptRole" ADD VALUE IF NOT EXISTS 'INTERN';
