ALTER TYPE "FrontOfficeRole" ADD VALUE 'HR_STAFF';
ALTER TYPE "FrontOfficeRole" ADD VALUE 'ASSET_STAFF';
ALTER TYPE "FrontOfficeRole" ADD VALUE 'FINANCE_STAFF';

ALTER TYPE "ReportStatus" ADD VALUE 'FIRST_APPROVED';
ALTER TYPE "ReportStatus" ADD VALUE 'SECOND_APPROVED';

ALTER TABLE "Report" ADD COLUMN "firstReviewerId"  INTEGER REFERENCES "User"("id");
ALTER TABLE "Report" ADD COLUMN "firstReviewedAt"  TIMESTAMP(3);
ALTER TABLE "Report" ADD COLUMN "secondReviewerId" INTEGER REFERENCES "User"("id");
ALTER TABLE "Report" ADD COLUMN "secondReviewedAt" TIMESTAMP(3);
