ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSET_REQUEST_SUBMITTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSET_REQUEST_LEADER_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSET_REQUEST_LEADER_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSET_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSET_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ASSET_REQUEST_FULFILLED';
